// Copyright 2024 BenderBlog Rodriguez and contributors.
// SPDX-License-Identifier: MPL-2.0
//
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum SaveToGroupIDPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct FileToGroupID: Hashable, CustomStringConvertible {
  var appid: String
  var fileName: String
  var data: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FileToGroupID? {
    let appid = pigeonVar_list[0] as! String
    let fileName = pigeonVar_list[1] as! String
    let data = pigeonVar_list[2] as! String

    return FileToGroupID(
      appid: appid,
      fileName: fileName,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      appid,
      fileName,
      data,
    ]
  }
  static func == (lhs: FileToGroupID, rhs: FileToGroupID) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SaveToGroupIDPigeonInternal.deepEquals(lhs.appid, rhs.appid) && SaveToGroupIDPigeonInternal.deepEquals(lhs.fileName, rhs.fileName) && SaveToGroupIDPigeonInternal.deepEquals(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FileToGroupID")
    SaveToGroupIDPigeonInternal.deepHash(value: appid, hasher: &hasher)
    SaveToGroupIDPigeonInternal.deepHash(value: fileName, hasher: &hasher)
    SaveToGroupIDPigeonInternal.deepHash(value: data, hasher: &hasher)
  }

  public var description: String {
    return "FileToGroupID(appid: \(String(describing: appid)), fileName: \(String(describing: fileName)), data: \(String(describing: data)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WatchSchedulePayload: Hashable, CustomStringConvertible {
  var json: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WatchSchedulePayload? {
    let json = pigeonVar_list[0] as! String

    return WatchSchedulePayload(
      json: json
    )
  }
  func toList() -> [Any?] {
    return [
      json
    ]
  }
  static func == (lhs: WatchSchedulePayload, rhs: WatchSchedulePayload) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SaveToGroupIDPigeonInternal.deepEquals(lhs.json, rhs.json)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WatchSchedulePayload")
    SaveToGroupIDPigeonInternal.deepHash(value: json, hasher: &hasher)
  }

  public var description: String {
    return "WatchSchedulePayload(json: \(String(describing: json)))"
  }
}

private class SaveToGroupIDPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return FileToGroupID.fromList(self.readValue() as! [Any?])
    case 130:
      return WatchSchedulePayload.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SaveToGroupIDPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FileToGroupID {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? WatchSchedulePayload {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SaveToGroupIDPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SaveToGroupIDPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SaveToGroupIDPigeonCodecWriter(data: data)
  }
}

class SaveToGroupIDPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SaveToGroupIDPigeonCodec(readerWriter: SaveToGroupIDPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SaveToGroupIdSwiftApi {
  func getHostLanguage() throws -> String
  func saveToGroupId(data: FileToGroupID, completion: @escaping (Result<Bool, Error>) -> Void)
  func deleteFromGroupId(data: FileToGroupID, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SaveToGroupIdSwiftApiSetup {
  static var codec: FlutterStandardMessageCodec { SaveToGroupIDPigeonCodec.shared }
  /// Sets up an instance of `SaveToGroupIdSwiftApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SaveToGroupIdSwiftApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getHostLanguageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.watermeter.SaveToGroupIdSwiftApi.getHostLanguage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getHostLanguageChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getHostLanguage()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getHostLanguageChannel.setMessageHandler(nil)
    }
    let saveToGroupIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.watermeter.SaveToGroupIdSwiftApi.saveToGroupId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveToGroupIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! FileToGroupID
        api.saveToGroupId(data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveToGroupIdChannel.setMessageHandler(nil)
    }
    let deleteFromGroupIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.watermeter.SaveToGroupIdSwiftApi.deleteFromGroupId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteFromGroupIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! FileToGroupID
        api.deleteFromGroupId(data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteFromGroupIdChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WatchSyncSwiftApi {
  func syncSchedule(payload: WatchSchedulePayload, completion: @escaping (Result<Bool, Error>) -> Void)
  func clearSchedule(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WatchSyncSwiftApiSetup {
  static var codec: FlutterStandardMessageCodec { SaveToGroupIDPigeonCodec.shared }
  /// Sets up an instance of `WatchSyncSwiftApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WatchSyncSwiftApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let syncScheduleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.watermeter.WatchSyncSwiftApi.syncSchedule\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncScheduleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! WatchSchedulePayload
        api.syncSchedule(payload: payloadArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      syncScheduleChannel.setMessageHandler(nil)
    }
    let clearScheduleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.watermeter.WatchSyncSwiftApi.clearSchedule\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearScheduleChannel.setMessageHandler { _, reply in
        api.clearSchedule { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearScheduleChannel.setMessageHandler(nil)
    }
  }
}
