plugins {
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.20' apply false
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.2.20'
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}
tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
