name: Release for Appimage

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install build-essential
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt install ninja-build
          sudo apt install -y libgtk-3-dev libfuse2
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          mv appimagetool /usr/local/bin/

      - name: Install Flutter
        run: |
          git submodule update --init --recursive

      - name: Prepare Flutter Dependencies
        run: |
          .flutter/bin/flutter config --no-analytics
          .flutter/bin/flutter pub get

      - name: Build Appimage
        run: |
          export PATH=$PATH:$PWD/.flutter/bin/
          dart pub global activate fastforge
          export PATH=$PATH:$HOME/.pub-cache/bin
          fastforge package --platform=linux --targets=appimage

      - name: Find Executable
        run: |
          export dir=$(find ./ -name watermeter-*)
          cp $dir ./watermeter.Appimage
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Watermeter_Appimage
          path: watermeter.Appimage
